### ISSUE TITLE
Suggest different templating operators

### ISSUE THREAD

**Issue by joshgoebel** [samsheff/Bunny#1]
If this is just for basic variable substation maybe something like Mustache {{variable}} syntax would be cleaner... and I'm not sure how you are ever going to do real Crystal code (since it needs to be compiled)... though perhaps you could build your own pseudo-templating language ALA Liquid or something.

**Comment by samsheff** [comment]
@yyyc514 I'm not against, but the reason I picked the ERB-like operators was the fact that Crystal's syntax is very similar to ruby, which makes migration and uptake less cumbersome. I'm also aware of a meta-programming approach to evaluate crystal code in the view and use that result (rather than just substituting strings).

If you'd like to submit a PR, please do!

**Comment by joshgoebel** [comment]
> the reason I picked the ERB-like operators was the fact that Crystal's syntax is very similar to ruby

Sure, but that doesn't matter much if you can't use Crystal code in the view (which I don't think you can do).  If you can pull that off though looking forward to seeing it. :-)

**Comment by joshgoebel** [comment]
If we can evaluate real code ERB syntax makes a lot of sense... but if not a simpler syntax might be better.

**Comment by samsheff** [comment]
@yyyc514 Well, it's definitely possible and already implemented via macros. See here: https://github.com/manastech/crystal/blob/master/CHANGELOG.md#020-2014-06-24

ERC (Embedded Crystal) has been working for a while, even before this library.

**Comment by joshgoebel** [comment]
Right, but those are all compile time things.  You can't load in a template (or string) someone provides you after your Crystal binary is built.  You can do it the same way ECR is doing it, but that's not dynamic, that's compiled.

What are you trying to accomplish here than ECR isn't doing already?

**Comment by samsheff** [comment]
Maybe I don't understand. Let's say I get string from a query parameter via frank, and I want to substitute that on the rendered page. The code I have will take that string and add it on the page in place of the ERB operators. ECR does something similar, but it evaluates code as well. What am I missing?

It's also worth mentioning that I wrote this before I found out about ECR, but whatever. It's a good learning experience.

**Comment by joshgoebel** [comment]
At run-time you can do string sub substitution... that's just basic string functions and a hash, as you already know.  What you can't do is run new code (code must be compiled)... 

Something like:

```
<%= @objects.each do |obj| %>
<%= obj.name %>
<% end %>
```

...is impossible at run-time... any templates used have to be compiled when the whole program is compiled (which is what ECR does).

**Comment by joshgoebel** [comment]
Well, not impossible... you could write your own language lexer, etc... but at that point it's not Crystal code, it's really something else.

**Comment by samsheff** [comment]
Sure, that makes sense. I'll close the issue since there's really nothing I can do about that and there's already a better solution.

**Comment by joshgoebel** [comment]
That's why I was suggesting maybe Mustache like syntax... that is a problem you can safely tackle at run-time without making people long for full-ERB syntax. :-) _shrugs_
